[package]
name = "algorithmic-art"
version = "0.1.0"
authors = ["Ryan P. Brewster <RyanPBrewster@gmail.com>"]

[dependencies]
image = "0.18"
rand = "0.4.2"
structopt = "0.1.7"
structopt-derive = "0.1.6"
